# Generated by Django 5.1.6 on 2025-02-19 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id_book', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Editorials',
            fields=[
                ('id_editorial', models.AutoField(primary_key=True, serialize=False)),
                ('editorial_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Copies',
            fields=[
                ('id_copy', models.AutoField(primary_key=True, serialize=False)),
                ('published_date', models.DateTimeField()),
                ('state', models.CharField(choices=[('Disponible', 'Disponible'), ('Prestado', 'Prestado')], max_length=50)),
                ('id_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.book')),
                ('id_editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.editorials')),
            ],
        ),
    ]
