# Generated by Django 5.1.6 on 2025-02-25 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
